# Use Ubuntu 20.04 as the base image
FROM ubuntu:20.04

# Maintainer information (using LABEL instead of MAINTAINER)
LABEL maintainer="ngocpq <phungquangngoc@gmail.com>"

#############################################################################
# Requirements
#############################################################################
ENV TZ=Australia/Melbourne
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Update package list and install required packages
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk openjdk-11-jdk openjdk-17-jdk git python3 wget tar

# Set environment variables for Java
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Copy the Oracle JDK 7 archive into the image
COPY jdk-7u80-linux-x64.tar /tmp/
# Install Java 7
RUN mkdir -p /usr/lib/jvm/java-7-oracle && \
    tar -xvf /tmp/jdk-7u80-linux-x64.tar -C /usr/lib/jvm/java-7-oracle --strip-components=1 && \
    rm /tmp/jdk-7u80-linux-x64.tar
# Maven 3.9.8 installation
RUN cd /opt && \
wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz && \
tar -xzf apache-maven-3.9.11-bin.tar.gz && \
mv apache-maven-3.9.11 maven

# Set environment variables for Maven
ENV M2_HOME=/opt/maven
ENV PATH=$M2_HOME/bin:$PATH

# Install Gradle
RUN apt-get install -y gradle

# Install xvfb
RUN apt-get install -y xvfb

ENV JAVA_OPTS="-Xmx4g -Xms512m"

#############################################################################
# Setup Validation tool
#############################################################################
# Create directory and setup validation tool
RUN mkdir /regression-validation

# Copy validation package and extract contents
COPY validation-package.jar /regminer4apr-validation/

# Extract validation package
RUN mkdir -p regminer4apr-validation && \
    cd /regminer4apr-validation && \
    jar xf validation-package.jar && \
    rm validation-package.jar

WORKDIR /regminer4apr-validation